### ISSUE TITLE
#1 Баз данных-ты настройкасын өзгертпе 

### ISSUE THREAD

**Issue by daucloudlab** [daucloudlab/boottest#2]
Қуаныш, баз данных-тың настройкасын өзгертпе! ОК?! Екеуміздікі бірдей болсын! Соны дұрыстап жібер!

**Comment by Kuanyshkntu** [comment]
Барды ма агай?

**Comment by daucloudlab** [comment]
Все дұрыс! Менің репозиториімді өзінің локальный репозиториіне git remote add деп менікің қосып ал! Fetch жасап жаңартып отырасын!

**Comment by Bakhytzhan96** [comment]
Agai mende cmd-ga mysql bolmai zhatyr?
